name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm audit fix
    - run: npm test

  # test action works running from the graph
  action:
    name: Test GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Locally
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "codescanalerts-action"
      - name: Checkout Github
        uses: actions/checkout@v2
        if: ${{ !env.ACT }}
      - name: on MTES-MCT/carbure and MTES-MCT/partaj
        uses: ./
        with:
          token: ${{ secrets.CODESCANALERTS_TOKEN }}
          repositories: MTES-MCT/carbure,MTES-MCT/partaj
          state: open
          output: codescanalerts.json
      - name: test output
        run: |
          echo $(cat codescanalerts.json)
          tool=$(echo $(cat codescanalerts.json | jq '.repositories | length'))
          if [[ ! "${tool[@]}" == 2 ]]; then
            exit 1
          fi
